apiVersion: ax.io/v1alpha1
kind: Task
metadata:
  name: state-probe
  atespace: default
spec:
  image: "localhost:5001/state-probe@sha256:3d5eae7a173e1ae8b0d1a6e7c7e0010df1638d6b0fbef7e6d6ba5d48292143c0"
  command:
    - python3
    - /app/probe.py
  env:
    - name: WORKSPACE
      value: "/workspace"
    - name: PROBE_HTTP_PORT
      value: "8080"
  debug: true
