apiVersion: ax.io/v1alpha1
kind: Task
metadata:
  name: openclaw-task
  atespace: default
spec:
  image: "localhost:5001/openclaw-agent@sha256:ebcf1473a83d16bc50a1199fae64824e1a08b3b9cd49dfffb8f5a8fcf0261be3"
  command:
    - /bin/bash
    - /agent/run_workload.sh
  env:
    - name: TARGET
      value: "security-target.default.svc.cluster.local"
    - name: SCAN_API_URL
      value: "http://external-scan-api:8080"
    - name: MCP_URL
      value: "http://external-mcp-server:8000/mcp"
    - name: TASK_NAME
      value: "openclaw-task"
    - name: WORKSPACE
      value: "/workspace"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://opentelemetry-collector.otel-system.svc.cluster.local:4318"
    - name: OTEL_SERVICE_NAME
      value: "openclaw-agent"
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: "http/protobuf"
  debug: true
